Update patch set 1
Patch Set 1:

Error: Package: python2-cliff-2.14.1-1.el7.noarch (build)
           Requires: python2-stevedore >= 1.20.0

Patch-set: 1